import Link from 'next/link'
import type { Metadata } from 'next'
import { getAppLoginUrl } from '@/lib/admin-session'
import SiteFooter from '@/components/SiteFooter'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'How AROFi and AROSOFT Innovations Ltd collect, use, and protect your data.',
  alternates: { canonical: 'https://arofi.net/privacy' },
}

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-slate-50 text-slate-900 font-sans antialiased">
      <nav className="home-nav" style={{ padding: '24px 24px 0' }}>
        <Link href="/" className="home-brand">
          <img src="/logo.png" alt="AROFi" />
          <span className="home-brand-text" aria-hidden="true">AROFi</span>
        </Link>
        <div className="home-nav-links">
          <Link href="/#features">Features</Link>
          <Link href="/#pricing">Pricing</Link>
          <Link href="/#faq">FAQ</Link>
          <Link href="/#contact">Contact</Link>
        </div>
        <div className="home-actions">
          <Link href="/docs" className="btn btn-ghost">Docs</Link>
          <a href={getAppLoginUrl()} className="btn btn-ghost">Sign In</a>
          <Link href="/?register=1" className="btn btn-primary">Register Free</Link>
        </div>
      </nav>

      <div className="legal-page">
        <h1>Privacy Policy</h1>
        <p className="legal-updated">Last updated: 8 July 2026</p>

        <div className="blog-post-content">
          <p>
            AROFi is operated by AROSOFT Innovations Ltd (&quot;AROSOFT&quot;, &quot;we&quot;, &quot;us&quot;), Kampala, Uganda.
            This policy explains what we collect from operators who use the AROFi platform and from
            customers who connect through AROFi-billed hotspots, and how we protect it.
          </p>

          <h2>What we collect</h2>
          <ul>
            <li><strong>Operator account data</strong> — name, email, phone number, business details, and compliance information you submit for review.</li>
            <li><strong>Billing data</strong> — package sales, voucher redemptions, mobile money transaction references, wallet balances and withdrawal records needed to run your billing.</li>
            <li><strong>Network session data</strong> — hotspot session records (device identifiers, connection times, data usage) generated by RADIUS authentication, used for billing, troubleshooting and the record-keeping expected of public internet providers.</li>
            <li><strong>Support conversations</strong> — messages you send via our chat, WhatsApp, email or the AI assistant.</li>
          </ul>

          <h2>How we use it</h2>
          <ul>
            <li>To operate hotspot billing: authenticate sessions, collect payments, credit wallets and process withdrawals.</li>
            <li>To meet legal and regulatory obligations that apply to public internet service provision in Uganda.</li>
            <li>To provide support and improve the platform.</li>
            <li>To send operational notifications (payment receipts, router-offline alerts, security notices).</li>
          </ul>

          <h2>What we do not do</h2>
          <ul>
            <li>We do not sell personal data to third parties.</li>
            <li>We do not read the content of your customers&apos; internet traffic.</li>
            <li>We do not use your data for advertising.</li>
          </ul>

          <h2>Security</h2>
          <p>
            Payments are processed through licensed mobile money providers and aggregators; card or wallet PINs never touch our systems.
            Each operator&apos;s data is isolated per business workspace, transport is encrypted (HTTPS/TLS), withdrawals require a separate secret code,
            and administrative access is protected with one-time email verification codes.
          </p>

          <h2>Retention and your rights</h2>
          <p>
            We keep records for as long as your account is active and as required by Ugandan law for financial and communications records.
            You may request a copy of your data, corrections, or deletion of your account by contacting
            {' '}<a href="mailto:support@arofi.net">support@arofi.net</a>. Some records (e.g. completed financial transactions) must be retained even after account closure.
          </p>

          <h2>Contact</h2>
          <p>
            AROSOFT Innovations Ltd, Kampala, Uganda ·{' '}
            <a href="mailto:support@arofi.net">support@arofi.net</a> · +256 787 726 388
          </p>
        </div>
      </div>

      <SiteFooter />
    </main>
  )
}
