ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "freeRouterLimit" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "proRouterLimit" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "enterpriseRouterLimit" INTEGER;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "freeAnalyticsHistoryDays" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "proAnalyticsHistoryDays" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "enterpriseAnalyticsHistoryDays" INTEGER;
