export type BookBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'ul'; items: string[] }
  | { type: 'ol'; items: string[] }
  | { type: 'callout'; tone: 'note' | 'success' | 'warning'; title: string; text: string }
  | { type: 'table'; headers: string[]; rows: string[][] }
  | { type: 'code'; title?: string; lines: string[] }
  | { type: 'image'; src: string; alt: string; caption: string }

export type BookPage = {
  slug: string
  chapter: string
  title: string
  summary: string
  audience: 'Everyone' | 'Business owner' | 'Network operator' | 'Platform administrator'
  blocks: BookBlock[]
}

export const arofiBook: BookPage[] = [
  {
    slug: 'start-here',
    chapter: 'Step 1',
    title: 'Start here: the correct operating order',
    summary: 'Follow this order from registration to the first verified customer connection.',
    audience: 'Everyone',
    blocks: [
      { type: 'image', src: '/brand/arofi-badge-blue.svg', alt: 'AROFi High Speed Zero Limits badge', caption: 'AROFi operations handbook — setup, selling, support and reconciliation.' },
      { type: 'h2', text: 'Complete the first setup in this order' },
      { type: 'ol', items: [
        'Register the business owner account and verify that sign-in works.',
        'Complete the business profile, support contacts and branding.',
        'Create the internet packages customers will buy.',
        'Add the MikroTik gateway router in AROFi.',
        'Run the generated onboarding script on that MikroTik only.',
        'Run the generated remote-access script when remote WinBox is required.',
        'Verify router heartbeat, RADIUS and captive-portal status in AROFi.',
        'Connect access points in bridge or access-point mode.',
        'Test one low-value Mobile Money purchase and one voucher redemption.',
        'Confirm the payment, wallet entry, voucher state and customer session before opening publicly.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Do not configure the upstream internet router', text: 'Run AROFi scripts only on the MikroTik gateway registered in AROFi. Do not paste them into an Airtel, MTN, fibre or other upstream internet router.' },
    ],
  },
  {
    slug: 'register-business',
    chapter: 'Step 2',
    title: 'Register the owner account and business',
    summary: 'Create the workspace that owns routers, packages, vouchers, agents and money.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Create the account' },
      { type: 'ol', items: [
        'Open AROFi and select Register Free.',
        'Enter the owner name, working phone number and email address.',
        'Create a strong password that is not reused on another service.',
        'Enter the business name customers should recognise.',
        'Select the required plan and submit registration.',
        'Sign in with the new account and open the business dashboard.',
      ] },
      { type: 'h2', text: 'Confirm before continuing' },
      { type: 'ul', items: [
        'The dashboard opens without an onboarding error.',
        'The correct business name is shown.',
        'The owner phone and email are correct.',
        'The selected workspace is the new business, not another tenant.',
      ] },
      { type: 'callout', tone: 'note', title: 'One owner account', text: 'Use named staff or agent accounts for daily work. Do not share the owner password between several people.' },
    ],
  },
  {
    slug: 'business-profile',
    chapter: 'Step 3',
    title: 'Complete profile, contacts and branding',
    summary: 'Set the information customers see on the portal, vouchers and support messages.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Complete business settings' },
      { type: 'ol', items: [
        'Open Settings from the dashboard.',
        'Enter the legal or trading name and the primary operating location.',
        'Add the support phone number customers can call or message.',
        'Add the support email address and confirm it can receive mail.',
        'Upload the approved business logo where custom branding is available.',
        'Choose the preferred blue, green or gold accent and save.',
        'Choose Light or Dark mode for the current device and save.',
        'Reload the page and confirm the logo, colour and mode remain saved.',
      ] },
      { type: 'callout', tone: 'success', title: 'Brand consistency', text: 'The public website and dashboard use the selected blue, green or gold AROFi identity. The hotspot portal also provides clean Light and Dark controls.' },
    ],
  },
  {
    slug: 'create-packages',
    chapter: 'Step 4',
    title: 'Create internet packages',
    summary: 'Define the price, time, speed, quota and device rules before selling access.',
    audience: 'Business owner',
    blocks: [
      { type: 'image', src: '/docs/package-controls.svg', alt: 'AROFi package controls', caption: 'Create clear packages, then use the small status control to publish or pause them.' },
      { type: 'h2', text: 'Create a normal internet package' },
      { type: 'ol', items: [
        'Open Packages.',
        'Select Add Package or Create Package.',
        'Choose Internet for a normal phone or computer package.',
        'Enter a short customer-friendly name such as 1 Hour, 4 Hours or 24 Hours.',
        'Enter the selling price in UGX.',
        'Set the exact duration.',
        'Set download and upload speed limits when required.',
        'Set a data quota only when the package should stop after a fixed amount of traffic.',
        'Set the device limit. Use one device for a normal package.',
        'Mark the package active and visible on the portal, then save.',
      ] },
      { type: 'h2', text: 'Create other package types' },
      { type: 'table', headers: ['Package type', 'How to set it up'], rows: [
        ['Multi-device', 'Choose Multi-device and set the maximum number of customer devices.'],
        ['Smart TV', 'Choose TV / Smart TV and use the television wireless MAC address during purchase.'],
        ['Free Trial', 'Open the built-in trial settings, set the allowed duration and enable or disable it.'],
      ] },
      { type: 'callout', tone: 'warning', title: 'Test the limits', text: 'Before publishing, buy the package on a test phone and confirm duration, speed, data quota and device count behave exactly as entered.' },
    ],
  },
  {
    slug: 'add-router',
    chapter: 'Step 5',
    title: 'Add a MikroTik router in AROFi',
    summary: 'Create the router record first so AROFi can generate unique setup scripts.',
    audience: 'Network operator',
    blocks: [
      { type: 'image', src: '/docs/router-ap-guide.svg', alt: 'MikroTik gateway and access points', caption: 'Add the MikroTik gateway first. Access points provide coverage but do not replace the gateway.' },
      { type: 'h2', text: 'Register the router' },
      { type: 'ol', items: [
        'Connect the MikroTik WAN port to the working internet router or modem.',
        'Connect the technician computer or phone to a MikroTik LAN port or its local WiFi.',
        'In AROFi, open Network or Routers.',
        'Select Add Router.',
        'Enter a clear name such as Shop 1 Gateway or Mutungo hEX.',
        'Enter the physical site or location.',
        'Enter the requested RouterOS or hardware details exactly where shown.',
        'Save the router.',
        'Open the new router record and locate the generated Onboarding Script and Remote Access Script.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Scripts are router-specific secrets', text: 'Never reuse one router script on another router. Do not publish generated scripts in screenshots, public chats or documents.' },
    ],
  },
  {
    slug: 'winbox-desktop',
    chapter: 'Step 6',
    title: 'Run the onboarding script in WinBox',
    summary: 'Paste the complete generated script into the registered MikroTik from a computer.',
    audience: 'Network operator',
    blocks: [
      { type: 'h2', text: 'Connect with WinBox' },
      { type: 'ol', items: [
        'Download WinBox only from the official MikroTik website.',
        'Open WinBox while the computer is connected to the MikroTik LAN.',
        'Select the router from Neighbors or enter its LAN IP address.',
        'Sign in with the router administrator username and password.',
        'Confirm the identity or model shown is the MikroTik added in AROFi.',
        'Open New Terminal.',
      ] },
      { type: 'h2', text: 'Run the AROFi script' },
      { type: 'ol', items: [
        'Return to AROFi and open the same router record.',
        'Copy the complete Onboarding Script using the copy button.',
        'Return to the WinBox terminal and paste the script once.',
        'Press Enter only when the terminal requires it.',
        'Wait until the script finishes. Do not close WinBox during execution.',
        'Read the final terminal output and note any red error line.',
        'Return to AROFi and refresh the router status.',
      ] },
      { type: 'code', title: 'Official WinBox download', lines: ['https://mikrotik.com/download/winbox'] },
      { type: 'callout', tone: 'warning', title: 'Do not paste line by line', text: 'Use the full script exactly as generated. Editing addresses, secrets, names or ports can break HotSpot, RADIUS or remote access.' },
    ],
  },
  {
    slug: 'mikrotik-mobile-terminal',
    chapter: 'Step 7',
    title: 'Run a MikroTik terminal from a mobile phone',
    summary: 'Use the official MikroTik Pro app when a computer is not available.',
    audience: 'Network operator',
    blocks: [
      { type: 'h2', text: 'Install the official app' },
      { type: 'ol', items: [
        'On the phone, open the official MikroTik Mobile Apps or Downloads page below.',
        'Choose MikroTik Pro, not MikroTik Home or Back To Home.',
        'Install the Android or iOS version from the store link shown by MikroTik.',
        'Connect the phone to the MikroTik LAN WiFi or to an access point already bridged to the MikroTik.',
        'Turn mobile data off temporarily so the phone stays on the local router network.',
      ] },
      { type: 'code', title: 'Official mobile app links', lines: [
        'https://mikrotik.com/mobile_app',
        'https://mikrotik.com/download/tools',
      ] },
      { type: 'h2', text: 'Connect and open Terminal' },
      { type: 'ol', items: [
        'Open MikroTik Pro.',
        'Select the detected router or enter its local IP address.',
        'Enter the RouterOS username and password, then tap Connect.',
        'Open the full or Advanced configuration menu.',
        'Open Terminal or New Terminal. The exact icon position can differ by app version.',
        'In AROFi, open the registered router and copy the complete Onboarding Script.',
        'Return to the terminal, paste the complete script once and run it.',
        'Keep the app open until the last command finishes.',
        'Return to AROFi and verify the router status.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Confirm the target first', text: 'Before pasting, verify the router identity, model or LAN IP. Never run the AROFi script on the upstream Airtel, MTN or fibre router.' },
    ],
  },
  {
    slug: 'remote-access-script',
    chapter: 'Step 8',
    title: 'Enable secure remote router access',
    summary: 'Run the second generated script only after onboarding is complete.',
    audience: 'Network operator',
    blocks: [
      { type: 'h2', text: 'Run the remote-access script' },
      { type: 'ol', items: [
        'Confirm the onboarding script completed and the router has internet.',
        'Open the router record in AROFi.',
        'Copy the Remote Access Script.',
        'Open New Terminal in WinBox or Terminal in MikroTik Pro.',
        'Paste and run the complete script once.',
        'Wait for the secure tunnel to connect.',
        'In AROFi, open the router remote-access controls.',
        'Use Test or Check Port before trying remote WinBox.',
        'Use the address and port displayed for that router.',
      ] },
      { type: 'callout', tone: 'note', title: 'No public port forwarding', text: 'Use the AROFi tunnel details. Do not open WinBox directly to the public internet and do not expose RouterOS management ports on the upstream router.' },
    ],
  },
  {
    slug: 'verify-router',
    chapter: 'Step 9',
    title: 'Verify router, RADIUS and portal status',
    summary: 'Do not sell access until every required status is confirmed.',
    audience: 'Network operator',
    blocks: [
      { type: 'h2', text: 'AROFi verification checklist' },
      { type: 'ol', items: [
        'Open Network or Routers and select the installed router.',
        'Confirm the router heartbeat or online state is current.',
        'Confirm the detected MikroTik model, RouterOS version and serial details look correct.',
        'Confirm RADIUS status is healthy.',
        'Confirm the captive portal file or portal status is healthy.',
        'Confirm the remote tunnel is connected when remote access was enabled.',
        'Open the live status or test control and correct every failed item before continuing.',
      ] },
      { type: 'h2', text: 'Local network check' },
      { type: 'ul', items: [
        'Customer devices receive a hotspot IP address from the MikroTik.',
        'The default gateway is the MikroTik hotspot address.',
        'The upstream internet router remains on the WAN side.',
        'Access points do not issue a second DHCP range.',
      ] },
      { type: 'callout', tone: 'success', title: 'Ready for portal testing', text: 'Continue only when the router is online, RADIUS is healthy and a client receives the expected hotspot network details.' },
    ],
  },
  {
    slug: 'access-points',
    chapter: 'Step 10',
    title: 'Connect and configure access points',
    summary: 'Extend WiFi coverage without creating a second router or bypassing the hotspot.',
    audience: 'Network operator',
    blocks: [
      { type: 'image', src: '/docs/router-ap-guide.svg', alt: 'MikroTik and indoor outdoor access point layout', caption: 'The MikroTik controls access. Access points bridge customers back to it.' },
      { type: 'h2', text: 'Configure each access point' },
      { type: 'ol', items: [
        'Connect the access point to a MikroTik LAN or hotspot bridge port.',
        'Open the access point management page or app.',
        'Select Access Point, Bridge or AP mode.',
        'Disable DHCP server, NAT and router mode on the access point.',
        'Set the customer SSID and wireless security required for the site.',
        'Give the access point a management IP that does not conflict with the MikroTik DHCP pool.',
        'Save and reboot the access point.',
        'Join the SSID with a phone and confirm the phone receives the MikroTik hotspot IP range.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Avoid double NAT', text: 'A Tenda, Grandstream or other access point in router mode can hide customer devices, create another DHCP network and prevent correct captive-portal or session tracking.' },
    ],
  },
  {
    slug: 'test-captive-portal',
    chapter: 'Step 11',
    title: 'Test the customer captive portal',
    summary: 'Prove that a new phone is redirected, can choose a package and can redeem a voucher.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Open the portal from a real customer phone' },
      { type: 'ol', items: [
        'Forget the hotspot WiFi network on the test phone.',
        'Reconnect to the hotspot SSID.',
        'Turn mobile data off for the test.',
        'Wait for the phone captive-portal notification.',
        'When no popup appears, open a normal HTTP website to trigger the redirect.',
        'Confirm the AROFi portal displays the business name, available packages and Voucher tab.',
        'Switch between Light and Dark and confirm both are readable.',
        'Switch blue, green and gold and confirm the badge and controls match the selected colour.',
      ] },
      { type: 'callout', tone: 'note', title: 'Popup behaviour belongs to the phone', text: 'Android, iPhone and computer operating systems decide when to show a captive-portal popup. The important test is that the local portal opens and the login flow completes.' },
    ],
  },
  {
    slug: 'test-mobile-money',
    chapter: 'Step 12',
    title: 'Run the first Mobile Money payment test',
    summary: 'Confirm collection, activation, wallet posting and session creation together.',
    audience: 'Business owner',
    blocks: [
      { type: 'image', src: '/docs/payment-flow.svg', alt: 'AROFi Mobile Money payment activation steps', caption: 'A provider-confirmed result activates internet access and records the financial entry.' },
      { type: 'h2', text: 'Test a low-value package' },
      { type: 'ol', items: [
        'Use a small active package created for testing.',
        'Join the hotspot with a test phone and open the portal.',
        'Select the package.',
        'Enter a valid MTN or Airtel Mobile Money number.',
        'Tap Pay and Connect.',
        'Approve the prompt on the payer phone using the correct PIN.',
        'Wait for AROFi to confirm the provider result and connect the customer.',
        'Open the dashboard and confirm the transaction status is successful.',
        'Confirm the business wallet entry and active session were created.',
        'Open a website on the customer phone to prove internet access.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Do not trust a browser message alone', text: 'Provider callback or status confirmation is authoritative. Never grant paid access only because a browser displayed a success message.' },
    ],
  },
  {
    slug: 'create-vouchers',
    chapter: 'Step 13',
    title: 'Create a voucher batch',
    summary: 'Generate traceable voucher stock for the owner or a named agent.',
    audience: 'Business owner',
    blocks: [
      { type: 'image', src: '/docs/voucher-workflow.svg', alt: 'AROFi voucher creation and assignment workflow', caption: 'A voucher batch is stock until a code is successfully redeemed.' },
      { type: 'h2', text: 'Generate the batch' },
      { type: 'ol', items: [
        'Open Vouchers.',
        'Select Create Batch or Generate Vouchers.',
        'Choose Main / Owner stock when the business will sell the vouchers directly.',
        'Choose an agent when the vouchers should be accountable to that agent.',
        'Select the internet package.',
        'Enter the quantity.',
        'Choose uppercase, lowercase, mixed or numeric code format.',
        'Choose the code length.',
        'Set an expiry date only when the stock must stop being valid on a fixed date.',
        'Review agent, location, package, quantity and value.',
        'Generate the batch once.',
      ] },
      { type: 'callout', tone: 'note', title: 'Generation is not a sale', text: 'Creating or assigning vouchers moves inventory. Revenue is recorded only after successful redemption.' },
    ],
  },
  {
    slug: 'print-vouchers',
    chapter: 'Step 14',
    title: 'Preview, download and print vouchers',
    summary: 'Produce the correct PDF and keep the batch traceable.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Download the printable PDF' },
      { type: 'ol', items: [
        'Open the newly created batch.',
        'Select Preview PDF.',
        'Check the business name, package, price, duration, code and QR on several vouchers.',
        'Check the assigned agent and location when the batch belongs to an agent.',
        'Download the PDF.',
        'Save it with the generated batch name.',
        'Print one test page before printing the full batch.',
        'Scan one QR while connected to the hotspot and confirm the correct code is submitted.',
      ] },
      { type: 'h2', text: 'After a QR routing update' },
      { type: 'ol', items: [
        'Do not delete or regenerate the voucher batch.',
        'Open the same existing batch after the new deployment.',
        'Download the PDF again so its printed QR contains the current local hotspot route.',
        'Replace old printed copies that still contain an obsolete public URL.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Printed QR codes cannot update themselves', text: 'A code printed on paper remains the same image. Re-download and reprint the same batch after QR URL changes.' },
    ],
  },
  {
    slug: 'test-voucher-qr',
    chapter: 'Step 15',
    title: 'Test voucher code and QR redemption',
    summary: 'Prove the local hotspot route, automatic code entry and internet activation.',
    audience: 'Network operator',
    blocks: [
      { type: 'h2', text: 'Test without consuming a real voucher' },
      { type: 'ol', items: [
        'Connect the phone to the customer hotspot WiFi.',
        'Turn mobile data off.',
        'Open the local test URL below.',
        'Confirm the AROFi portal opens.',
        'Confirm the voucher tab opens and automatic verification runs.',
        'Confirm an invalid-voucher message appears for the test code.',
      ] },
      { type: 'code', title: 'Local routing test', lines: ['http://10.55.0.1/login?voucher=TEST-NOT-VALID'] },
      { type: 'h2', text: 'Test one real voucher' },
      { type: 'ol', items: [
        'Scan a QR from the newly downloaded PDF while still connected to hotspot WiFi.',
        'Confirm the local portal opens instead of a public-site connection error.',
        'Wait for the code to be verified automatically.',
        'Confirm the phone connects to the internet.',
        'Open the voucher batch and confirm the code is Redeemed.',
        'Confirm the sale, wallet entry and active session are visible.',
      ] },
      { type: 'callout', tone: 'note', title: 'Local route works only on the hotspot', text: 'The 10.55.0.1 address is intentionally local. It should be opened while the phone is connected to the AROFi hotspot, not from mobile data or another network.' },
    ],
  },
  {
    slug: 'create-agent',
    chapter: 'Step 16',
    title: 'Create a voucher sales agent',
    summary: 'Register the person, location and commission before assigning stock.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Add the agent' },
      { type: 'ol', items: [
        'Open Agents.',
        'Select Add Agent or Register Agent.',
        'Enter the agent full name.',
        'Enter a unique agent code when requested.',
        'Enter the working phone number.',
        'Enter the assigned territory, branch or selling location.',
        'Enter the commission rate approved for that agent.',
        'Set the agent status to Active.',
        'Save the record.',
        'Open the saved agent and confirm name, code, phone, location and commission are correct.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Use one record per person', text: 'Do not reuse one agent account for several sellers. Named records are required for stock, sales, commission and cash accountability.' },
    ],
  },
  {
    slug: 'assign-agent-vouchers',
    chapter: 'Step 17',
    title: 'Assign vouchers to an agent',
    summary: 'Move a specific batch or quantity into the agent stock record.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Issue stock' },
      { type: 'ol', items: [
        'Open the agent record or the voucher issuance panel.',
        'Select Assign Vouchers, Issue Stock or Generate Agent Vouchers.',
        'Choose the agent.',
        'Confirm the selling location.',
        'Choose the package and quantity.',
        'Review the total stock value and expected commission.',
        'Confirm the assignment once.',
        'Download or print the agent voucher PDF.',
        'Give the agent the matching physical or digital vouchers.',
        'Open the accountability report and confirm the quantity appears under Assigned and Available.',
      ] },
      { type: 'callout', tone: 'success', title: 'Traceability check', text: 'The voucher PDF, batch, agent record and location report should all show the same assigned agent and site.' },
    ],
  },
  {
    slug: 'agent-stock-actions',
    chapter: 'Step 18',
    title: 'Return, reassign or void voucher stock',
    summary: 'Correct stock without deleting the audit history.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Handle unsold stock' },
      { type: 'ol', items: [
        'Open the agent or voucher batch.',
        'Filter for Available vouchers only.',
        'Select the required stock action: return, reassign or void.',
        'Enter the reason and destination agent or owner stock when required.',
        'Review the affected quantity before confirming.',
        'Confirm once and wait for the updated totals.',
        'Check the original agent report and the destination report.',
        'Destroy or withdraw printed vouchers that were voided.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Redeemed vouchers cannot become stock again', text: 'Never attempt to reassign or sell a redeemed code. Use only available, unexpired vouchers for stock transfers.' },
    ],
  },
  {
    slug: 'agent-accountability',
    chapter: 'Step 19',
    title: 'Reconcile agent sales, commission and cash due',
    summary: 'Use redeemed vouchers and settlements to calculate what the agent must remit.',
    audience: 'Business owner',
    blocks: [
      { type: 'image', src: '/docs/live-dashboard.svg', alt: 'AROFi agent and voucher sales dashboard', caption: 'Compare assigned stock, available stock, redeemed value, commission and settlements.' },
      { type: 'h2', text: 'Reconcile an agent' },
      { type: 'ol', items: [
        'Open the Agent Voucher Accountability report.',
        'Select the agent and date range.',
        'Confirm Assigned, Available, Redeemed, Expired and Voided quantities.',
        'Confirm Gross Sales equals the value of successfully redeemed agent vouchers.',
        'Confirm Commission uses the agent rate stored on the sale.',
        'Confirm Cash Due reflects gross sales less commission and completed settlement coverage.',
        'Record the cash or Mobile Money amount received from the agent using the settlement workflow.',
        'Export or save the report and give the agent a copy.',
      ] },
      { type: 'callout', tone: 'note', title: 'Use redemption date for sales', text: 'Assigned vouchers are inventory. Count revenue only when a voucher is successfully redeemed.' },
    ],
  },
  {
    slug: 'manage-sessions',
    chapter: 'Step 20',
    title: 'Monitor customers and active sessions',
    summary: 'See who is online, inspect package state and disconnect access when required.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Check a customer session' },
      { type: 'ol', items: [
        'Open Sessions or Customers.',
        'Filter by router, site, phone, MAC address or status.',
        'Open the customer or session detail.',
        'Check package name, start time, expiry, data use and device details.',
        'Confirm the session is linked to the correct payment or voucher.',
        'Use Disconnect or Revoke only when access must end immediately.',
        'Refresh and confirm the router no longer reports the session as active.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Do not use idle time as package expiry', text: 'A valid paid package should end through its duration, quota, explicit revocation or authoritative RADIUS control, not an accidental short local idle timeout.' },
    ],
  },
  {
    slug: 'wallet-withdrawal',
    chapter: 'Step 21',
    title: 'Check the wallet and request a withdrawal',
    summary: 'Withdraw only confirmed available business earnings to an approved number.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Review the balance' },
      { type: 'ol', items: [
        'Open Wallet or Withdrawals.',
        'Check Available, Reserved and Total balance separately.',
        'Open recent entries and confirm successful sales are present.',
        'Confirm failed or reversed transactions were not counted as available earnings.',
      ] },
      { type: 'h2', text: 'Request the withdrawal' },
      { type: 'ol', items: [
        'Select an approved MTN or Airtel payout number.',
        'Enter an amount not greater than the available balance.',
        'Enter the withdrawal security code or requested authentication.',
        'Review the network, number, amount and fee.',
        'Submit once and wait for the provider result.',
        'Confirm the withdrawal becomes Completed or Failed instead of remaining unexplained.',
        'Check the phone and wallet ledger after completion.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Reserved is not available', text: 'A pending withdrawal reserves funds so the same money cannot be withdrawn twice. Do not create repeated requests while one is still being processed.' },
    ],
  },
  {
    slug: 'reports-exports',
    chapter: 'Step 22',
    title: 'Run reports and export records',
    summary: 'Reconcile payments, voucher sales, agents, wallets, routers and sessions.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Create a daily or monthly report' },
      { type: 'ol', items: [
        'Open Reports.',
        'Select the required date range and business location.',
        'Filter by payment network, router, package, voucher batch or agent when required.',
        'Compare successful payments with wallet credits.',
        'Compare redeemed vouchers with voucher revenue.',
        'Compare agent redeemed value, commission and settlements.',
        'Review failed payments, reversals, expired stock and offline routers separately.',
        'Export CSV, spreadsheet or PDF where the page provides that option.',
        'Store the export using the business name and reporting period.',
      ] },
      { type: 'callout', tone: 'success', title: 'Close the period', text: 'A period is reconciled when successful sales, wallet entries, withdrawals, agent settlements and exceptions can all be explained.' },
    ],
  },
  {
    slug: 'staff-users',
    chapter: 'Step 23',
    title: 'Add staff users and control access',
    summary: 'Give each staff member only the permissions needed for their work.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Create a staff user' },
      { type: 'ol', items: [
        'Open Users or Team.',
        'Select Add User or Invite User.',
        'Enter the staff member name, email and phone.',
        'Choose the correct business workspace.',
        'Assign the smallest suitable role or permission set.',
        'Send the invitation.',
        'Ask the staff member to create a private password.',
        'Sign in with the new account during testing and confirm restricted areas are hidden.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Remove access immediately', text: 'Disable or remove users and agents as soon as they leave the business or no longer need access.' },
    ],
  },
  {
    slug: 'notifications-support',
    chapter: 'Step 24',
    title: 'Use notifications, support and issue records',
    summary: 'Record the evidence needed to resolve router, payment and account problems quickly.',
    audience: 'Everyone',
    blocks: [
      { type: 'h2', text: 'Before contacting support' },
      { type: 'ol', items: [
        'Open the affected router, payment, voucher, withdrawal or session record.',
        'Copy the record ID, router name, site and exact time of failure.',
        'Capture the first clear error message or first red terminal line.',
        'For payments, include the provider reference and phone network but never the customer PIN.',
        'For vouchers, include the batch name and masked code.',
        'For router setup, include model, RouterOS version and status checks without exposing script secrets.',
        'Open Support or the chat widget and submit one complete issue record.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Never send secrets', text: 'Do not send Mobile Money PINs, withdrawal security codes, passwords, API keys or complete router scripts in a public message.' },
    ],
  },
  {
    slug: 'platform-admin',
    chapter: 'Step 25',
    title: 'Platform administrator operating steps',
    summary: 'Manage tenants, users, gateways, fees, compliance and platform withdrawals.',
    audience: 'Platform administrator',
    blocks: [
      { type: 'h2', text: 'Review a business tenant' },
      { type: 'ol', items: [
        'Open the platform command centre or Tenants.',
        'Search for the business by name, owner, phone or email.',
        'Open the tenant and verify subscription, status, wallets, routers and compliance state.',
        'Use impersonation or support access only through approved platform controls and only for the required task.',
        'Record every status, fee, compliance or access change.',
      ] },
      { type: 'h2', text: 'Operate payment settings safely' },
      { type: 'ol', items: [
        'Open platform payment or gateway settings.',
        'Confirm the intended environment before entering test or live credentials.',
        'Update one provider configuration at a time.',
        'Save, then run a controlled low-value collection test.',
        'Run a controlled disbursement test only after live-wallet approval.',
        'Check callbacks, status polling, wallet posting and error handling.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Tenant money remains isolated', text: 'A business can withdraw only its own eligible earnings. Platform commission and business earnings must remain in their correct wallets.' },
    ],
  },
  {
    slug: 'troubleshooting',
    chapter: 'Step 26',
    title: 'Troubleshoot in the correct order',
    summary: 'Use one evidence-based sequence instead of resetting devices or changing many settings at once.',
    audience: 'Network operator',
    blocks: [
      { type: 'h2', text: 'When the portal does not open' },
      { type: 'ol', items: [
        'Confirm the phone is connected to the hotspot SSID and mobile data is off.',
        'Check the phone IP address and default gateway.',
        'Confirm the gateway is the MikroTik hotspot address.',
        'Open the local MikroTik login address directly.',
        'Check HotSpot, DHCP and bridge status on the MikroTik.',
        'Check AROFi router heartbeat, RADIUS and portal-file status.',
        'Change only the first failed layer, then test again.',
      ] },
      { type: 'h2', text: 'When payment succeeds but internet does not open' },
      { type: 'ol', items: [
        'Open the payment and confirm provider status is successful.',
        'Confirm an activation record and reconnect credentials were created.',
        'Confirm RADIUS is reachable from the router.',
        'Confirm the customer MAC and hotspot server are correct.',
        'Check the active session and router log for the first authentication error.',
      ] },
      { type: 'h2', text: 'When a voucher QR fails' },
      { type: 'ol', items: [
        'Confirm the phone is on hotspot WiFi.',
        'Read the QR destination and confirm it uses the local hotspot login route.',
        'Open the local TEST-NOT-VALID URL to prove routing and automatic submission.',
        'Re-download the existing batch PDF after a QR routing deployment.',
        'Test one newly downloaded QR before printing the full batch.',
      ] },
      { type: 'callout', tone: 'warning', title: 'Do not reset the upstream router', text: 'A reset can remove the working internet connection and does not repair an AROFi portal, RADIUS or voucher problem. Diagnose the first failed layer.' },
    ],
  },
  {
    slug: 'daily-checklist',
    chapter: 'Step 27',
    title: 'Daily opening and closing checklist',
    summary: 'A short repeatable routine for reliable hotspot operations.',
    audience: 'Business owner',
    blocks: [
      { type: 'h2', text: 'Opening checks' },
      { type: 'ol', items: [
        'Confirm every operating router is online.',
        'Confirm RADIUS and payment gateways show no active failure.',
        'Open the customer portal from one test phone.',
        'Check available voucher stock and expiring batches.',
        'Check pending withdrawals and unresolved support tickets.',
        'Confirm agents have the correct stock for the day.',
      ] },
      { type: 'h2', text: 'Closing checks' },
      { type: 'ol', items: [
        'Review the day sales and successful payment count.',
        'Review voucher redemptions and agent cash due.',
        'Review failed payments, reversals and unusual session activity.',
        'Confirm wallet movement and completed withdrawals.',
        'Export or save the daily report.',
        'Record offline routers and unresolved exceptions for follow-up.',
      ] },
      { type: 'callout', tone: 'success', title: 'One source of truth', text: 'Use AROFi records for stock, sales, commission, sessions and wallet reconciliation. Avoid separate untraceable paper totals.' },
    ],
  },
]
