export const PERMISSIONS = {
  all: 'ALL',
  tenantsRead: 'tenants.read',
  tenantsManage: 'tenants.manage',
  usersRead: 'users.read',
  usersManage: 'users.manage',
  packagesRead: 'packages.read',
  packagesManage: 'packages.manage',
  vouchersRead: 'vouchers.read',
  vouchersManage: 'vouchers.manage',
  billingRead: 'billing.read',
  billingWrite: 'billing.write',
  paymentsRead: 'payments.read',
  agentsRead: 'agents.read',
  agentsManage: 'agents.manage',
  floatManage: 'float.manage',
  disbursementsRead: 'disbursements.read',
  disbursementsManage: 'disbursements.manage',
  routersRead: 'routers.read',
  routersManage: 'routers.manage',
  hotspotsRead: 'hotspots.read',
  hotspotsManage: 'hotspots.manage',
  sessionsRead: 'sessions.read',
  reportsRead: 'reports.read',
  settingsManage: 'settings.manage',
  supportRead: 'support.read',
  supportWrite: 'support.write',
  auditRead: 'audit.read',
  featureLimitsRead: 'feature_limits.read',
  featureLimitsManage: 'feature_limits.manage',
  referralsRead: 'referrals.read',
  referralsManage: 'referrals.manage',
  referralWithdrawalsManage: 'referral_withdrawals.manage',
} as const

export const STANDARD_ROLE_CATALOG: Record<string, string[]> = {
  // ALL remains authoritative. support.read is also explicit because the
  // ticket-floor client uses it to identify staff-facing workflow controls.
  SuperAdmin: [PERMISSIONS.all, PERMISSIONS.supportRead],
  VendorAdmin: [
    PERMISSIONS.tenantsRead,
    PERMISSIONS.usersRead,
    PERMISSIONS.usersManage,
    PERMISSIONS.packagesRead,
    PERMISSIONS.packagesManage,
    PERMISSIONS.vouchersRead,
    PERMISSIONS.vouchersManage,
    PERMISSIONS.billingRead,
    PERMISSIONS.billingWrite,
    PERMISSIONS.paymentsRead,
    PERMISSIONS.agentsRead,
    PERMISSIONS.agentsManage,
    PERMISSIONS.floatManage,
    PERMISSIONS.disbursementsRead,
    PERMISSIONS.disbursementsManage,
    PERMISSIONS.routersRead,
    PERMISSIONS.routersManage,
    PERMISSIONS.hotspotsRead,
    PERMISSIONS.hotspotsManage,
    PERMISSIONS.sessionsRead,
    PERMISSIONS.reportsRead,
    PERMISSIONS.settingsManage,
    PERMISSIONS.supportRead,
    PERMISSIONS.supportWrite,
    PERMISSIONS.auditRead,
    PERMISSIONS.featureLimitsRead,
    PERMISSIONS.referralsRead,
  ],
  ResellerPartner: [
    PERMISSIONS.referralsRead,
    PERMISSIONS.referralWithdrawalsManage,
    PERMISSIONS.supportRead,
    PERMISSIONS.supportWrite,
  ],
  Support: [
    PERMISSIONS.supportRead,
    PERMISSIONS.supportWrite,
    PERMISSIONS.sessionsRead,
    PERMISSIONS.vouchersRead,
    PERMISSIONS.paymentsRead,
    PERMISSIONS.tenantsRead,
    PERMISSIONS.hotspotsRead,
    PERMISSIONS.routersRead,
  ],
  NetworkOperator: [
    PERMISSIONS.routersRead,
    PERMISSIONS.routersManage,
    PERMISSIONS.hotspotsRead,
    PERMISSIONS.hotspotsManage,
    PERMISSIONS.sessionsRead,
    PERMISSIONS.packagesRead,
    PERMISSIONS.vouchersRead,
    PERMISSIONS.settingsManage,
    PERMISSIONS.tenantsRead,
    PERMISSIONS.supportRead,
    PERMISSIONS.supportWrite,
  ],
  WifiAdmin: [
    PERMISSIONS.routersRead,
    PERMISSIONS.routersManage,
    PERMISSIONS.hotspotsRead,
    PERMISSIONS.hotspotsManage,
    PERMISSIONS.sessionsRead,
    PERMISSIONS.packagesRead,
    PERMISSIONS.packagesManage,
    PERMISSIONS.vouchersRead,
    PERMISSIONS.vouchersManage,
    PERMISSIONS.agentsRead,
    PERMISSIONS.tenantsRead,
    PERMISSIONS.supportRead,
    PERMISSIONS.supportWrite,
  ],
  VoucherAgent: [
    PERMISSIONS.packagesRead,
    PERMISSIONS.vouchersRead,
    PERMISSIONS.vouchersManage,
    PERMISSIONS.billingRead,
    PERMISSIONS.agentsRead,
    PERMISSIONS.tenantsRead,
  ],
  FinanceManager: [
    PERMISSIONS.billingRead,
    PERMISSIONS.billingWrite,
    PERMISSIONS.paymentsRead,
    PERMISSIONS.agentsRead,
    PERMISSIONS.floatManage,
    PERMISSIONS.disbursementsRead,
    PERMISSIONS.disbursementsManage,
    PERMISSIONS.reportsRead,
    PERMISSIONS.tenantsRead,
    PERMISSIONS.supportRead,
    PERMISSIONS.supportWrite,
  ],
  ReadOnlySupport: [
    PERMISSIONS.tenantsRead,
    PERMISSIONS.packagesRead,
    PERMISSIONS.vouchersRead,
    PERMISSIONS.billingRead,
    PERMISSIONS.paymentsRead,
    PERMISSIONS.agentsRead,
    PERMISSIONS.routersRead,
    PERMISSIONS.hotspotsRead,
    PERMISSIONS.sessionsRead,
    PERMISSIONS.supportRead,
  ],
}
