export const PERMISSIONS = {
  all: 'ALL',
  tenantsRead: 'tenants.read',
  tenantsManage: 'tenants.manage',
  usersRead: 'users.read',
  usersManage: 'users.manage',
  packagesRead: 'packages.read',
  packagesManage: 'packages.manage',
  vouchersRead: 'vouchers.read',
  vouchersManage: 'vouchers.manage',
  billingRead: 'billing.read',
  billingWrite: 'billing.write',
  paymentsRead: 'payments.read',
  agentsRead: 'agents.read',
  agentsManage: 'agents.manage',
  floatManage: 'float.manage',
  disbursementsRead: 'disbursements.read',
  disbursementsManage: 'disbursements.manage',
  routersRead: 'routers.read',
  routersManage: 'routers.manage',
  hotspotsRead: 'hotspots.read',
  hotspotsManage: 'hotspots.manage',
  sessionsRead: 'sessions.read',
  reportsRead: 'reports.read',
  settingsManage: 'settings.manage',
  supportRead: 'support.read',
  supportWrite: 'support.write',
  auditRead: 'audit.read',
  featureLimitsRead: 'feature_limits.read',
  featureLimitsManage: 'feature_limits.manage',
} as const

export const STANDARD_ROLE_CATALOG: Record<string, string[]> = {
  SuperAdmin: [PERMISSIONS.all],
  VendorAdmin: [
    PERMISSIONS.tenantsRead,
    PERMISSIONS.usersRead,
    PERMISSIONS.usersManage,
    PERMISSIONS.packagesRead,
    PERMISSIONS.packagesManage,
    PERMISSIONS.vouchersRead,
    PERMISSIONS.vouchersManage,
    PERMISSIONS.billingRead,
    PERMISSIONS.billingWrite,
    PERMISSIONS.paymentsRead,
    PERMISSIONS.agentsRead,
    PERMISSIONS.agentsManage,
    PERMISSIONS.floatManage,
    PERMISSIONS.disbursementsRead,
    PERMISSIONS.disbursementsManage,
    PERMISSIONS.routersRead,
    PERMISSIONS.routersManage,
    PERMISSIONS.hotspotsRead,
    PERMISSIONS.hotspotsManage,
    PERMISSIONS.sessionsRead,
    PERMISSIONS.reportsRead,
    PERMISSIONS.settingsManage,
    PERMISSIONS.supportRead,
    PERMISSIONS.supportWrite,
    PERMISSIONS.auditRead,
    PERMISSIONS.featureLimitsRead,
  ],
  Finance: [
    PERMISSIONS.billingRead,
    PERMISSIONS.billingWrite,
    PERMISSIONS.paymentsRead,
    PERMISSIONS.disbursementsRead,
    PERMISSIONS.disbursementsManage,
    PERMISSIONS.agentsRead,
    PERMISSIONS.reportsRead,
    PERMISSIONS.tenantsRead,
  ],
  Support: [
    PERMISSIONS.supportRead,
    PERMISSIONS.supportWrite,
    PERMISSIONS.sessionsRead,
    PERMISSIONS.vouchersRead,
    PERMISSIONS.paymentsRead,
    PERMISSIONS.tenantsRead,
    PERMISSIONS.hotspotsRead,
    PERMISSIONS.routersRead,
  ],
  NetworkOperator: [
    PERMISSIONS.routersRead,
    PERMISSIONS.routersManage,
    PERMISSIONS.hotspotsRead,
    PERMISSIONS.hotspotsManage,
    PERMISSIONS.sessionsRead,
    PERMISSIONS.packagesRead,
    PERMISSIONS.vouchersRead,
    PERMISSIONS.settingsManage,
    PERMISSIONS.tenantsRead,
  ],
}
